In [4]:
# Import the standard libraries 
import numpy as np 
import pandas as pd
import glob 
import os 

# Dir
data_dir = '/Users/quocanh1306/Downloads/'

In [5]:
# Check the noisy and pristine files 
noisy_file = 'hlsp_deepmerge_hst-jwst_acs-wfc3-nircam_illustris-z2_f814w-f160w-f356w_v1_sim-noisy-x.npy'
pristine_file = 'hlsp_deepmerge_hst-jwst_acs-wfc3-nircam_illustris-z2_f814w-f160w-f356w_v1_sim-pristine-x.npy'

# Read the npy files 
noisy_data = np.load(data_dir + noisy_file)
pristine_data = np.load(data_dir + pristine_file)

In [61]:
print(pristine_data)
print(len(pristine_data))

[[[[1.29983451e-03 1.15692807e-03 1.32012070e-03 ... 8.34456579e-03
    7.94480372e-03 7.69893989e-03]
   [1.10559631e-03 9.81278774e-04 1.15786827e-03 ... 1.04445281e-02
    1.09854654e-02 7.83246887e-03]
   [8.56316526e-04 1.26611394e-03 9.50716940e-04 ... 1.17158704e-02
    1.30717568e-02 1.13337496e-02]
   ...
   [1.64880769e-02 9.65646689e-03 5.30145590e-03 ... 1.29521029e-02
    1.27369516e-02 1.11135848e-02]
   [9.06795217e-03 5.37327266e-03 3.25374098e-03 ... 1.74333192e-02
    1.73936420e-02 1.51278471e-02]
   [6.53830386e-03 4.17372702e-03 3.23871522e-03 ... 2.17031910e-02
    2.39803383e-02 1.65577993e-02]]

  [[1.91066275e-03 2.05998886e-03 2.16990068e-03 ... 1.26623624e-02
    1.19729155e-02 1.09253165e-02]
   [1.87178545e-03 2.01444062e-03 2.10953264e-03 ... 1.50235152e-02
    1.56984692e-02 1.25227928e-02]
   [2.07164560e-03 2.43922502e-03 2.22465722e-03 ... 1.71324693e-02
    1.84252328e-02 1.68627408e-02]
   ...
   [1.68557968e-02 1.25382871e-02 8.83009373e-03 ... 1.01197713e-02
    9.98428028e-03 9.37047168e-03]
   [1.15142493e-02 9.46023863e-03 7.26990521e-03 ... 1.19398423e-02
    1.20593947e-02 1.12014934e-02]
   [9.25119788e-03 7.63358495e-03 6.59201048e-03 ... 1.31280901e-02
    1.45801476e-02 1.08566716e-02]]

  [[9.07855554e-03 9.31794848e-03 1.02686038e-02 ... 7.11283011e-02
    7.03432306e-02 5.61811982e-02]
   [1.05520637e-02 1.26942067e-02 1.28369963e-02 ... 9.39260990e-02
    9.27000726e-02 6.84345732e-02]
   [1.24093668e-02 1.45076209e-02 1.46021703e-02 ... 1.05989139e-01
    1.08054506e-01 8.13313999e-02]
   ...
   [5.25884665e-02 5.63890113e-02 5.02435976e-02 ... 3.29546470e-02
    3.17048429e-02 2.40293009e-02]
   [4.94655869e-02 5.32545622e-02 4.96216848e-02 ... 3.06704198e-02
    2.90688970e-02 2.20567095e-02]
   [3.80278920e-02 3.77796746e-02 3.76353975e-02 ... 2.35865853e-02
    2.24680264e-02 1.78588497e-02]]]


 [[[3.30941151e-04 3.59306241e-04 3.13172968e-04 ... 1.63580124e-02
    1.50479228e-02 1.50030308e-02]
   [2.47797155e-04 3.32203864e-04 2.48788917e-04 ... 1.27371148e-02
    1.31756991e-02 1.20370596e-02]
   [2.74999767e-04 3.64708437e-04 3.38904544e-04 ... 1.10960714e-02
    9.70757900e-03 1.09762083e-02]
   ...
   [1.82660998e-03 1.74607747e-03 1.61081278e-03 ... 8.36861959e-03
    9.26552841e-03 9.01022873e-03]
   [1.62653521e-03 1.51529085e-03 1.67039356e-03 ... 1.15460612e-02
    1.35716154e-02 8.92746376e-03]
   [1.48036680e-03 1.40550534e-03 1.63114071e-03 ... 1.33898076e-02
    1.43499966e-02 1.05276779e-02]]

  [[1.54036997e-03 1.64425559e-03 1.68244092e-03 ... 1.31853410e-02
    1.19485407e-02 1.23562560e-02]
   [1.38450642e-03 1.68599183e-03 1.73695648e-03 ... 1.18709027e-02
    1.19849415e-02 1.11635258e-02]
   [1.52408267e-03 2.12431649e-03 2.08296526e-03 ... 1.16637500e-02
    1.03935904e-02 1.07094864e-02]
   ...
   [6.00469108e-03 6.09515843e-03 6.26932910e-03 ... 8.94134050e-03
    1.06060200e-02 1.09084494e-02]
   [5.30092796e-03 5.58167019e-03 5.96693986e-03 ... 9.72572394e-03
    1.15000848e-02 9.57965026e-03]
   [4.52146264e-03 4.97425368e-03 5.41399179e-03 ... 9.65482142e-03
    1.08092298e-02 8.88333048e-03]]

  [[9.40081397e-03 1.17631394e-02 1.26905630e-02 ... 3.02991672e-02
    2.99529628e-02 2.42105936e-02]
   [1.29554699e-02 1.59691637e-02 1.78200059e-02 ... 3.87411213e-02
    3.70307858e-02 2.82970514e-02]
   [1.39187612e-02 1.82713874e-02 1.92324199e-02 ... 4.28090456e-02
    4.02855289e-02 2.96612300e-02]
   ...
   [4.07256627e-02 4.89718083e-02 5.05984222e-02 ... 3.93652202e-02
    4.50359142e-02 4.25724621e-02]
   [3.64175406e-02 4.53055148e-02 4.99700464e-02 ... 3.25608533e-02
    3.83306812e-02 2.96391410e-02]
   [2.52815325e-02 3.33909596e-02 3.73062152e-02 ... 2.13330448e-02
    2.38391224e-02 2.11946367e-02]]]


 [[[4.53661896e-03 3.99689758e-03 4.63338067e-03 ... 9.39477944e-04
    1.09823980e-03 9.32854293e-04]
   [5.77365651e-03 5.33316240e-03 4.77320807e-03 ... 1.41236957e-03
    1.53131211e-03 1.06299681e-03]
   [6.44194089e-03 4.71388429e-03 4.66930737e-03 ... 1.74028117e-03
    1.35389095e-03 1.08105528e-03]
   ...
   [9.75496712e-02 1.43690150e-01 2.97408176e-01 ... 5.07499133e-04
    6.67838364e-04 1.00024347e-03]
   [5.76123804e-02 8.46048225e-02 1.32741991e-01 ... 4.64829026e-04
    1.02587807e-03 7.46944891e-04]
   [3.54516159e-02 5.67753111e-02 6.58629910e-02 ... 8.42276455e-04
    6.16029070e-04 1.12045762e-03]]

  [[5.68548627e-03 5.81001439e-03 6.64563804e-03 ... 2.02311988e-03
    2.15981048e-03 1.86852526e-03]
   [7.06211806e-03 7.43999769e-03 7.48753837e-03 ... 2.88058071e-03
    2.76864404e-03 2.01231365e-03]
   [8.03545163e-03 7.15315598e-03 7.36036066e-03 ... 3.49306252e-03
    2.78346589e-03 2.23987024e-03]
   ...
   [7.40195319e-02 1.10281213e-01 2.14733678e-01 ... 1.49147068e-03
    1.47403756e-03 1.61424984e-03]
   [4.33825222e-02 6.40236123e-02 9.78797899e-02 ... 1.43109286e-03
    1.87350070e-03 1.58134709e-03]
   [2.65506028e-02 3.98482091e-02 4.72189769e-02 ... 1.78659363e-03
    1.51942695e-03 1.70043282e-03]]

  [[1.87471118e-02 2.28101141e-02 2.46794459e-02 ... 1.10634954e-02
    1.01036836e-02 9.37946672e-03]
   [2.45138650e-02 3.04212599e-02 3.24917180e-02 ... 1.60639862e-02
    1.49003388e-02 9.36707155e-03]
   [2.76566905e-02 3.16195662e-02 3.47421206e-02 ... 1.80719847e-02
    1.58497762e-02 1.13041727e-02]
   ...
   [1.21179921e-01 1.79075985e-01 2.95940770e-01 ... 1.08666737e-02
    1.03166869e-02 7.32911173e-03]
   [7.85531019e-02 1.12489044e-01 1.54835381e-01 ... 1.09406712e-02
    1.03368131e-02 8.44787293e-03]
   [4.80048398e-02 6.54706267e-02 7.69756195e-02 ... 9.38229815e-03
    8.80585349e-03 6.68652885e-03]]]


 ...


 [[[1.32040185e-06 4.86423713e-07 1.83356390e-06 ... 1.17573287e-07
    1.10351960e-07 1.36635504e-08]
   [6.13433128e-07 5.67445358e-07 8.50571049e-07 ... 2.03574813e-07
    1.17597493e-07 3.53741577e-07]
   [1.39571670e-06 5.78415080e-07 1.28281950e-06 ... 6.14524741e-07
    4.62832873e-07 6.07169160e-08]
   ...
   [9.81081274e-06 1.42499004e-05 1.33626536e-05 ... 4.45116981e-07
    6.12708053e-07 2.13728469e-07]
   [1.57138401e-05 1.31346885e-05 1.05920036e-05 ... 2.27436253e-07
    1.40927130e-07 2.03133834e-07]
   [7.98043427e-06 9.83672298e-06 7.60052456e-06 ... 1.06593671e-06
    7.42891959e-08 5.79837148e-07]]

  [[1.96289236e-06 8.30222427e-07 2.70548632e-06 ... 2.78071608e-07
    1.79919128e-07 3.75278335e-08]
   [1.21146635e-06 1.27688628e-06 1.58797292e-06 ... 3.10185297e-07
    2.87584360e-07 5.31716396e-07]
   [2.22523422e-06 1.00465186e-06 1.62779009e-06 ... 8.39070985e-07
    7.98066072e-07 2.04197989e-07]
   ...
   [1.23272170e-05 1.79006512e-05 1.61982185e-05 ... 1.09921984e-06
    1.01332620e-06 4.85283368e-07]
   [1.75523327e-05 1.62044527e-05 1.41542898e-05 ... 9.16939051e-07
    4.39158520e-07 6.69178423e-07]
   [9.30969057e-06 1.18722521e-05 9.98734857e-06 ... 1.60744297e-06
    2.45227144e-07 1.15681174e-06]]

  [[2.14487892e-06 4.61895356e-06 1.09646714e-05 ... 3.19580293e-06
    1.71724372e-06 3.43699708e-07]
   [2.74266618e-06 4.81019101e-06 8.46994992e-06 ... 1.65413674e-06
    1.50165942e-06 1.63340842e-06]
   [6.39272616e-06 5.81098450e-06 6.06949728e-06 ... 2.14777010e-06
    2.88533128e-06 1.35397364e-06]
   ...
   [3.38030613e-05 4.93337077e-05 4.30781476e-05 ... 4.75488172e-06
    3.54390323e-06 2.56844507e-06]
   [3.63616337e-05 4.17761595e-05 4.27117220e-05 ... 5.52248899e-06
    3.26924450e-06 1.81129459e-06]
   [2.36224026e-05 2.97206755e-05 2.68677136e-05 ... 3.99467181e-06
    2.06694686e-06 4.25047767e-06]]]


 [[[6.64887158e-07 6.65690124e-07 3.60370158e-07 ... 2.52728485e-08
    3.78163185e-07 9.46128153e-08]
   [1.07576197e-06 1.13003770e-07 1.35811364e-07 ... 4.01740811e-07
    1.29842899e-07 2.50196342e-07]
   [3.33864145e-07 5.64728622e-07 4.90800650e-07 ... 5.12694726e-07
    2.98984920e-07 3.02620199e-07]
   ...
   [2.10011236e-08 2.60177003e-08 1.57184912e-07 ... 1.52644875e-06
    9.87457032e-07 1.74052074e-06]
   [5.63091695e-07 5.49043351e-08 1.95956509e-07 ... 2.33888175e-06
    1.53921177e-06 5.30401803e-07]
   [9.63387722e-08 2.48200299e-07 1.74512485e-07 ... 3.12133733e-06
    3.14526574e-06 2.56887446e-06]]

  [[8.78758229e-07 7.42249672e-07 5.89451473e-07 ... 6.66208753e-08
    6.34634335e-07 1.67104688e-07]
   [1.37309180e-06 2.82019728e-07 2.85379974e-07 ... 7.50172861e-07
    4.42496690e-07 3.92914850e-07]
   [5.35141900e-07 1.17616050e-06 6.65590154e-07 ... 1.03489913e-06
    7.84143503e-07 7.98731528e-07]
   ...
   [9.90089816e-08 1.10432238e-07 5.53750402e-07 ... 2.63923680e-06
    1.74179035e-06 2.33974122e-06]
   [8.82363395e-07 3.07314088e-07 7.68239488e-07 ... 3.18349195e-06
    2.41981850e-06 1.09226525e-06]
   [4.84190449e-07 4.69585208e-07 8.71273984e-07 ... 3.82007901e-06
    3.34108715e-06 2.94127149e-06]]

  [[3.34573799e-06 9.60180366e-07 1.43862436e-06 ... 8.04604736e-07
    2.95210330e-06 4.93981736e-07]
   [2.81774182e-06 1.84225226e-06 1.91706776e-06 ... 3.04646305e-06
    3.38629603e-06 1.85285934e-06]
   [2.11574153e-06 5.44921532e-06 1.88748430e-06 ... 4.37065453e-06
    2.03403139e-06 2.59083360e-06]
   ...
   [1.20474214e-06 1.45720094e-06 2.97107143e-06 ... 9.11591999e-06
    6.37799077e-06 5.61773240e-06]
   [2.84362627e-06 2.80192305e-06 2.83337853e-06 ... 1.13889413e-05
    1.00868690e-05 4.09280322e-06]
   [9.29512516e-07 1.69360309e-06 2.07199708e-06 ... 8.15412034e-06
    5.11050748e-06 8.47323152e-06]]]


 [[[5.13507553e-07 9.34570329e-07 7.10043695e-08 ... 2.86541486e-06
    4.90948634e-07 4.25700235e-07]
   [1.74457214e-07 1.53534395e-07 7.19232211e-08 ... 6.74388556e-07
    1.05573416e-06 4.65213801e-07]
   [2.68778625e-07 3.51549937e-07 2.48990724e-07 ... 2.06894360e-06
    1.29002391e-06 1.44390169e-06]
   ...
   [6.76977338e-08 8.39543296e-07 7.10653834e-07 ... 1.77949349e-06
    2.34120527e-06 3.58483567e-06]
   [1.99675653e-07 1.17942994e-07 3.50675469e-07 ... 1.81311458e-06
    2.00605374e-06 1.98139382e-06]
   [6.40837555e-08 1.02221163e-07 3.69073141e-07 ... 1.30387841e-06
    1.11648773e-06 1.51747114e-06]]

  [[6.37550107e-07 1.39109555e-06 2.05885408e-07 ... 3.45362457e-06
    8.78903805e-07 6.54838819e-07]
   [3.41510567e-07 4.60326331e-07 2.57573741e-07 ... 1.38560848e-06
    1.66194621e-06 8.43007876e-07]
   [5.13353510e-07 6.14834581e-07 7.85766101e-07 ... 2.79667147e-06
    2.01561498e-06 2.33479254e-06]
   ...
   [2.15522270e-07 1.27454494e-06 1.28232196e-06 ... 2.59457236e-06
    3.36005899e-06 3.88792707e-06]
   [5.85673873e-07 3.29825016e-07 6.97565173e-07 ... 3.05260657e-06
    2.81648657e-06 3.00231436e-06]
   [1.62621542e-07 2.03765161e-07 5.93714769e-07 ... 1.72535435e-06
    1.19277868e-06 1.76807076e-06]]

  [[2.24707053e-06 3.96372332e-06 1.11752280e-06 ... 6.66895606e-06
    2.45807109e-06 1.00443272e-06]
   [2.68015424e-06 4.13745007e-06 2.41257862e-06 ... 7.90681341e-06
    5.25047688e-06 2.13329562e-06]
   [2.87900426e-06 3.91733025e-06 3.85421848e-06 ... 8.05056697e-06
    5.81708061e-06 7.80934789e-06]
   ...
   [3.37136113e-06 4.30612310e-06 5.33761254e-06 ... 8.72110925e-06
    8.81787696e-06 5.79891567e-06]
   [1.86925290e-06 1.55051645e-06 3.83780961e-06 ... 8.49770504e-06
    6.66931830e-06 7.25220673e-06]
   [3.41044416e-07 6.92942296e-07 2.83546942e-06 ... 4.37147090e-06
    5.82091390e-06 2.57346531e-06]]]]
15426

In [9]:
# importing Illustris catalog
catalog_new = []
catalog_new = np.genfromtxt(data_dir + 'illustris_morphs_rf.txt', dtype=None)
catalog = pd.DataFrame(catalog_new)
catalog.columns =  ['snap','subid','logmstar','cam','merger','rfprob','asym_I','cc_I','g_I','m20_I','mprime_I','asym_H','cc_H','g_H','m20_H','mprime_H','t_lastmaj','t_lastmin','t_nextmaj','t_nextmin']
catalog

/var/folders/fw/_vv3v5xx4237m2_lkjg3_0s00000gn/T/ipykernel_89123/17464870.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  catalog_new = np.genfromtxt(data_dir + 'illustris_morphs_rf.txt', dtype=None)

,snap,subid,logmstar,cam,merger,rfprob,asym_I,cc_I,g_I,m20_I,mprime_I,asym_H,cc_H,g_H,m20_H,mprime_H,t_lastmaj,t_lastmin,t_nextmaj,t_nextmin
0,103,0,12.20,0,False,b'0.103',0.2076,2.9771,0.5534,-1.4073,-1.3047,0.1193,3.6158,0.5952,-1.9186,-1.5796,-2.6956,-0.6481,4.4276,50.0000
1,103,0,12.20,3,False,b'0.15',0.2082,3.6671,0.5881,-1.5640,-1.1394,0.1433,3.8279,0.5921,-1.9774,-1.2196,-2.6956,-0.6481,4.4276,50.0000
2,103,0,12.20,1,False,b'0.132',0.2069,3.6939,0.6117,-1.5015,-1.0887,0.1663,3.8399,0.5917,-1.8892,-1.2522,-2.6956,-0.6481,4.4276,50.0000
3,103,0,12.20,2,False,b'0.231',0.2195,3.2588,0.5904,-1.5522,-1.3975,0.1482,3.8950,0.6085,-2.0038,-1.3152,-2.6956,-0.6481,4.4276,50.0000
4,103,19702,12.12,3,False,b'None',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5016,-1.4423,50.0000,50.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71946,54,18603,9.83,2,False,b'None',-0.0648,2.6204,0.4758,-1.2925,-0.3358,-0.1215,2.2644,0.4750,-1.4103,-0.5217,-1.0475,-50.0000,10.5717,50.0000
71947,54,8205,9.82,1,False,b'None',0.0134,2.4736,0.4804,-1.5007,-1.1829,-0.1366,2.4745,0.5023,-1.5417,0.2205,-0.3715,-0.5883,0.2776,0.6182
71948,54,8205,9.82,3,False,b'None',0.0519,2.4502,0.4625,-1.3560,-0.8130,-0.1186,2.5425,0.4749,-1.5294,0.2499,-0.3715,-0.5883,0.2776,0.6182
71949,54,8205,9.82,2,False,b'None',0.1353,2.1423,0.4737,-1.2310,-0.5579,-0.0662,2.2829,0.4540,-1.4985,0.2494,-0.3715,-0.5883,0.2776,0.6182
71950,54,8205,9.82,0,False,b'None',0.1309,2.4773,0.4857,-1.3748,-0.6035,-0.1294,2.4766,0.4684,-1.6014,0.2461,-0.3715,-0.5883,0.2776,0.6182

In [10]:
# extract only objects from snapshot 68 (which is for z=2)
merged_68 = catalog.loc[catalog['snap'] == 68]
merged_68

,snap,subid,logmstar,cam,merger,rfprob,asym_I,cc_I,g_I,m20_I,mprime_I,asym_H,cc_H,g_H,m20_H,mprime_H,t_lastmaj,t_lastmin,t_nextmaj,t_nextmin
52329,68,0,11.88,0,True,b'None',NaN,NaN,NaN,NaN,NaN,0.0860,2.8530,0.5463,-1.8116,-1.3221,-0.4537,-0.4537,0.1655,3.4351
52330,68,0,11.88,1,True,b'None',NaN,NaN,NaN,NaN,NaN,0.0738,2.8770,0.5526,-1.7441,-1.3423,-0.4537,-0.4537,0.1655,3.4351
52331,68,0,11.88,3,True,b'None',NaN,NaN,NaN,NaN,NaN,0.0911,2.8247,0.5340,-1.7679,-1.3116,-0.4537,-0.4537,0.1655,3.4351
52332,68,0,11.88,2,True,b'None',NaN,NaN,NaN,NaN,NaN,0.0769,2.7880,0.5358,-1.7708,-1.3380,-0.4537,-0.4537,0.1655,3.4351
52333,68,14557,11.63,0,False,b'0.221',0.1312,3.4661,0.4992,-1.9007,-0.8344,0.0462,3.7150,0.5528,-2.0840,-1.5967,-1.9574,-1.3663,50.0000,3.4351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61254,68,114316,9.83,0,False,b'None',-0.1116,2.0279,0.4731,-0.9225,-0.3593,-0.1375,2.3497,0.4938,-1.3445,0.1868,-2.0436,-50.0000,0.6268,50.0000
61255,68,122676,9.81,3,False,b'None',-0.1379,NaN,NaN,NaN,NaN,-0.1232,NaN,NaN,NaN,NaN,-1.3663,-50.0000,0.6268,50.0000
61256,68,122676,9.81,1,False,b'None',-0.1723,NaN,NaN,NaN,NaN,-0.2282,NaN,NaN,NaN,NaN,-1.3663,-50.0000,0.6268,50.0000
61257,68,122676,9.81,2,False,b'None',0.0405,NaN,NaN,NaN,NaN,-0.2032,NaN,NaN,NaN,NaN,-1.3663,-50.0000,0.6268,50.0000
61258,68,122676,9.81,0,False,b'None',-0.2230,NaN,NaN,NaN,NaN,-0.1487,NaN,NaN,NaN,NaN,-1.3663,-50.0000,0.6268,50.0000

#Produce the merger sample

In [11]:
# producting an array with objects used in RF + all object with p_RF=None which were excluded in RF
temp = np.array(merged_68.copy(), dtype=None)
rf_objects = []
for i in range(len(temp)):
    rf_objects.append([temp[i,1],temp[i,4]])
rf_objects = np.stack(rf_objects)

#object IDs, which are needed to find these objects in the image files
subid, indices = np.unique(rf_objects[:,0], return_index=True)
RF_labels = rf_objects[indices]

In [12]:
shid_array = RF_labels[:,0]
merger_labels = RF_labels[:,1]

In [ ]:
print(shid_array)
len(merger_labels)

[     0      1      2 ... 199156 204341 207613]

2233

In [103]:
list_of_mergers=[]
list_of_nonmergers=[]

In [48]:
#subdirs for displaying
path = '/Users/quocanh1306/Downloads/DeepMerge/data/resized_SB25'
subdirs = ['res_subdir_{josh:03d}'.format(josh=x) for x in range(23)]

In [104]:
#All 4 filters i order ['ACS-F435W', ACS-F814W','NC-F356W','WFC3-F160W'], we will need second and fourth:
for shid, merger in zip(shid_array,merger_labels):
    for camnum in ['00','01','02','03']:
            filter_files=np.sort(np.asarray(glob.glob(os.path.join(path,'res_sub*','*sh'+str(shid)+'cam'+camnum+'*SB25.npy'))))
            # the above should return exactly 4 files

            tmp= np.zeros((4, 75, 75))
     

            if bool(merger) is True:
               list_of_mergers.append(tmp)

            else:
                list_of_nonmergers.append(tmp)

In [105]:
mergers = np.stack(list_of_mergers)
notmergers = np.stack(list_of_nonmergers)
mergers_y = np.ones(mergers.shape[0])
notmergers_y = np.zeros(notmergers.shape[0])

In [106]:
X = np.vstack((mergers, notmergers))
y = np.concatenate((mergers_y, notmergers_y))

In [107]:
print(len(mergers_y))
print(len(notmergers_y))
print(len(y))

1624
7308
8932

In [78]:
np.save('/Users/quocanh1306/Downloads/SB25.npy', X)
np.save('/Users/quocanh1306/Downloads/SB25_y.npy', y)

In [80]:
XX = np.load('/Users/quocanh1306/Downloads/SB25.npy')
yy = np.load('/Users/quocanh1306/Downloads/SB25_y.npy')

In [82]:
len(yy)

8932

In [108]:
xx_data_list = []
for i in range(len(X)):
    xx_data_list.append([X[i,1],X[i,3]])
xx_data = np.stack(xx_data_list)
yy_data = y

In [109]:
list_ud = []
list_lr = []
list_rot = []
list_rot180 = []

for i in range(0,1624):
    tmp = np.zeros((3, 75, 75))
    tmp[0,:,:]=np.flipud(xx_data[i,0])
    tmp[1,:,:]=np.flipud(xx_data[i,1])
    list_ud.append(tmp)
    
    
for i in range(0,1624):
    tmp = np.zeros((3, 75, 75))
    tmp[0,:,:]=np.fliplr(xx_data[i,0])
    tmp[1,:,:]=np.fliplr(xx_data[i,1])
    list_lr.append(tmp)
    
    
for i in range(0,1624):
    tmp = np.zeros((3, 75, 75))
    tmp[0,:,:]=np.rot90(xx_data[i,0])
    tmp[1,:,:]=np.rot90(xx_data[i,1])
    list_rot.append(tmp)
    
    
for i in range(0,1624):
    tmp = np.zeros((3, 75, 75))
    tmp[0,:,:]=np.rot90(np.rot90(xx_data[i,0]))
    tmp[1,:,:]=np.rot90(np.rot90(xx_data[i,1]))
    list_rot180.append(tmp)

In [110]:
mergers_ud = np.stack(list_ud)
mergers_lr = np.stack(list_lr)
mergers_rot = np.stack(list_rot)
mergers_rot180 = np.stack(list_rot180)

In [111]:
y_ud = np.ones(mergers_ud.shape[0])
y_lr = np.ones(mergers_lr.shape[0])
y_rot = np.ones(mergers_rot.shape[0])
y_rot180 = np.ones(mergers_rot180.shape[0])

In [113]:
#X_augmented = np.vstack((xx_data[:1624], mergers_ud, mergers_lr, mergers_rot, mergers_rot180, xx_data[1624:]))
y_augmented = np.concatenate((yy_data[:1624], y_ud, y_lr, y_rot, y_rot180, yy_data[1624:]))

In [121]:
np.shape(y_augmented)

(15428,)

In [123]:
np.save('/Users/quocanh1306/Downloads/SB25_augmented_y.npy', y_augmented)